<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateEspecies extends Migration{
	public function up(){ 
 		Schema::create('especies', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->string('nombre_cientifico');
			$table->string('nombre_comun');
			$table->string('description');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}