<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'especie_id',
        'recinto_id',
        'actividad_id',
        'edad',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie' , 'especie_id');
    }

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto' , 'recinto_id');
    }

    public function actividads()
    {
        return $this->belongsToMany('App\Models\Actividad' , 'actividad_id');
    }

    public function cuidadoranimals()
    {
        return $this->hasMany('App\Models\CuidadorAnimal');
    }
}
